/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AkunController;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class FormUtama extends javax.swing.JFrame {

    public JLabel getA() {
        return a;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public JTextField getUser() {
        return user;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JTextField getPass() {
        return pass;
    }

    public JTextField getPasskon() {
        return passkon;
    }

    public JTextField getPassnew() {
        return passnew;
    }

    public JComboBox<String> getStatus() {
        return status;
    }

    public JLabel getKet() {
        return ket;
    }

    /**
     * Creates new form FormUtama
     */
    
    AkunController akunController;
    FormLogin view;
    
    public FormUtama() {
        initComponents();
        awal();
        view = new FormLogin();
        akunController = new AkunController(view, this);
    }
    
    private void awal(){
        juser.setVisible(false);
        user.setVisible(false);
        jpass.setVisible(false);
        pass.setVisible(false);
        jStatus.setVisible(false);
        status.setVisible(false);
        jpassnew.setVisible(false);
        passnew.setVisible(false);
        jkonpass.setVisible(false);
        passkon.setVisible(false);
        btnInsert.setVisible(false);
        Home.setVisible(true);
    }
    
    public void pushInsert(){
        juser.setVisible(true);
        user.setVisible(true);
        jpass.setVisible(true);
        pass.setVisible(true);
        jStatus.setVisible(true);
        status.setVisible(true);
        jpassnew.setVisible(false);
        passnew.setVisible(false);
        jkonpass.setVisible(false);
        passkon.setVisible(false);
        btnInsert.setVisible(true);
        Home.setVisible(false);
        jLabel4.setText("Edit Akun");
    }
    
    public void editPass(){
        juser.setVisible(true);
        user.setVisible(true);
        jpass.setVisible(true);
        jpass.setText("Password Lama");
        pass.setVisible(true);
        jpassnew.setVisible(true);
        passnew.setVisible(true);
        jkonpass.setVisible(true);
        passkon.setVisible(true);
        btnInsert.setVisible(true);
        btnInsert.setText("Update");
        Home.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        juser = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jkonpass = new javax.swing.JLabel();
        passkon = new javax.swing.JTextField();
        jpass = new javax.swing.JLabel();
        jpassnew = new javax.swing.JLabel();
        passnew = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jStatus = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        btnInsert = new javax.swing.JButton();
        jInsert = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackGround = new javax.swing.JPanel();
        a = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Pembayaran");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 350, 132, 29);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Home");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 160, 70, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Penyewaan");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 250, 121, 29);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Pemesanan");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 300, 132, 29);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Report");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 390, 71, 29);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Keluar");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 440, 67, 29);

        jLabel20.setText("FUTSAL TIME");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(44, 511, 100, 14);

        jLabel21.setText("1.0");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(66, 525, 90, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setText("HOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 170, 44);

        jLabel13.setText("-----------------------------------------");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 140, 170, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Pelanggan");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jLabel22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel22KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(20, 200, 109, 29);

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Selamat Datang!");

        jLabel5.setText("Anda Login Sebagai :");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addGap(0, 308, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Home);
        Home.setBounds(360, 140, 590, 330);

        juser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        juser.setText("Username :");
        getContentPane().add(juser);
        juser.setBounds(360, 140, 100, 30);
        getContentPane().add(user);
        user.setBounds(360, 170, 170, 30);

        jkonpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jkonpass.setText("Konfirmasi Password :");
        getContentPane().add(jkonpass);
        jkonpass.setBounds(360, 360, 180, 30);
        getContentPane().add(passkon);
        passkon.setBounds(360, 390, 170, 30);

        jpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpass.setText("Password :");
        getContentPane().add(jpass);
        jpass.setBounds(360, 220, 190, 30);

        jpassnew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpassnew.setText("Password Baru :");
        getContentPane().add(jpassnew);
        jpassnew.setBounds(360, 290, 140, 30);
        getContentPane().add(passnew);
        passnew.setBounds(360, 320, 170, 30);
        getContentPane().add(pass);
        pass.setBounds(360, 250, 170, 30);

        jStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jStatus.setText("Level :");
        getContentPane().add(jStatus);
        jStatus.setBounds(580, 224, 110, 20);

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "operator" }));
        getContentPane().add(status);
        status.setBounds(580, 250, 130, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(610, 390, 80, 30);

        jInsert.setBackground(new java.awt.Color(255, 255, 255));
        jInsert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInsertMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tambah Akun");

        javax.swing.GroupLayout jInsertLayout = new javax.swing.GroupLayout(jInsert);
        jInsert.setLayout(jInsertLayout);
        jInsertLayout.setHorizontalGroup(
            jInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInsertLayout.setVerticalGroup(
            jInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInsertLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jInsert);
        jInsert.setBounds(1000, 520, 120, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 600);

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(BackGround);
        BackGround.setBounds(0, 0, 1150, 560);
        getContentPane().add(a);
        a.setBounds(10, 60, 90, 30);

        setSize(new java.awt.Dimension(1166, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel22KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22KeyPressed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        FormBooking sewa = new FormBooking();
        if (a.getText().equals("operator")) {
            sewa.getjLabel18().setVisible(false);
            sewa.getA().setText(a.getText());
            sewa.getUser().setText(user.getText());
        }
        sewa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        FormMember member = new FormMember();
        if (a.getText().equals("operator")) {
            member.getjLabel18().setVisible(false);
            member.getA().setText(a.getText());
            member.getUser().setText(user.getText());
        }
        member.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        FormPemesanan pesan = new FormPemesanan();
        if (a.getText().equals("operator")) {
            pesan.getjLabel18().setVisible(false);
            pesan.getA().setText(a.getText());
            pesan.getUser().setText(user.getText());
            pesan.getTambahbrg().setVisible(false);
        }
        pesan.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        FormPembayaran bayar = new FormPembayaran();
        if (a.getText().equals("operator")) {
            bayar.getjLabel18().setVisible(false);
            bayar.getA().setText(a.getText());
            bayar.getUser().setText(user.getText());
        }
        bayar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        new FormReport().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInsertMouseClicked
        if (jLabel4.getText().equalsIgnoreCase("tambah akun")) {
            pushInsert();
        } else{
            editPass();
        }
    }//GEN-LAST:event_jInsertMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if (btnInsert.getText().equalsIgnoreCase("insert")) {
            akunController.insert();
            user.setText("");
            pass.setText("");
            awal();
        } else{
            akunController.update();
            pass.setText("");
            passnew.setText("");
            passkon.setText("");
            if (a.getText().equals("admin")) {
                user.setText("");
            }
            awal();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Home;
    public javax.swing.JLabel a;
    private javax.swing.JButton btnInsert;
    private javax.swing.JPanel jInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jkonpass;
    private javax.swing.JLabel jpass;
    private javax.swing.JLabel jpassnew;
    private javax.swing.JLabel juser;
    private javax.swing.JLabel ket;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField passkon;
    private javax.swing.JTextField passnew;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
